=== cpp-love/The-Hidden-Route/schema/level-v0.1.0-4.schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "title": "关卡数据样式",
    "description": "此格式为关卡数据的样式，用于存储关卡。",
    "type": "object",
    "properties": {
        "segments": {
            "title": "迷宫路径中的一段路径",
            "description": "这些路径将用来操控玩家行走。",
            "type": "array",
            "items": {
                "title": "迷宫路径中直的一段",
                "type": "object",
                "properties": {
                    "prev": {
                        "title": "路径（起始位置）连接的前面一个路径实体",
                        "description": "应填写列表的索引（从 0 开始计数），且不应超过列表的最大索引；若没有，填写 null。",
                        "oneOf": [
                            {
                                "type": "integer",
                                "minimum": 0
                            },
                            {
                                "type": "null"
                            }
                        ],
                        "default": null
                    },
                    "next": {
                        "title": "路径（终止位置）连接的后面一个路径实体",
                        "description": "应填写列表的索引（从 0 开始计数），且不应超过列表的最大索引；若没有，填写 null。",
                        "oneOf": [
                            {
                                "type": "integer",
                                "minimum": 0
                            },
                            {
                                "type": "null"
                            }
                        ],
                        "default": null
                    },
                    "start_center": {
                        "title": "路径起始位置的中心点",
                        "$ref": "types.schema.json#/$defs/vector2f"
                    },
                    "length": {
                        "title": "路径段的长度",
                        "type": "number",
                        "minimum": 0.0
                    },
                    "walked_precent": {
                        "title": "路径段的被走过的百分比",
                        "type": "number",
                        "minimum": 0.0,
                        "maximum": 1.0,
                        "default": 0.0
                    },
                    "dir": {
                        "title": "线段的方向",
                        "description": "从起始位置到终止位置的方向。",
                        "type": "string",
                        "enum": [
                            "right",
                            "down",
                            "left",
                            "up"
                        ]
                    },
                    "tags": {
                        "title": "路径段的标签",
                        "description": "用于标记路径段的标签列表。",
                        "type": "array",
                        "items": {
                            "title": "一个标签",
                            "type": "integer"
                        },
                        "default": []
                    }
                },
                "required": [
                    "start_center",
                    "length",
                    "dir"
                ]
            },
            "minItems": 1
        },
        "line_strips": {
            "title": "迷宫中的折线",
            "description": "只是一些装饰性的折线，不操控玩家。",
            "type": "object",
            "properties": {
                "width": {
                    "title": "折线宽度",
                    "type": "number",
                    "minimum": 0.0,
                    "default": 5.0
                },
                "color": {
                    "title": "折线颜色",
                    "$ref": "types.schema.json#/$defs/color"
                },
                "vertexs": {
                    "title": "所有折线的点集",
                    "type": "array",
                    "items": {
                        "title": "一条折线的点集",
                        "type": "array",
                        "items": {
                            "title": "一个点",
                            "$ref": "types.schema.json#/$defs/vector2f"
                        },
                        "minItems": 1
                    },
                    "default": []
                }
            }
        },
        "level_script": {
            "title": "关卡对应的脚本",
            "description": "关卡脚本的文件名（相对于 `assets/lua_scripts/` 目录），若没有则为 null。",
            "type": [
                "string",
                "null"
            ],
            "default": null
        },
        "level_info": {
            "title": "关卡信息",
            "properties": {
                "start_segment_entity": {
                    "title": "起始段落对应的实体",
                    "description": "应填写段落列表的索引（从 0 开始计数），且不应超过列表的最大索引；若没有，填写 null。",
                    "type": "integer",
                    "minimum": 0
                },
                "end_segment_entity": {
                    "title": "结束段落对应的实体",
                    "description": "应填写段落列表的索引（从 0 开始计数），且不应超过列表的最大索引；若没有，填写 null。",
                    "type": "integer",
                    "minimum": 0
                }
            },
            "required": [
                "start_segment_entity",
                "end_segment_entity"
            ]
        }
    },
    "required": [
        "level_info",
        "segments"
    ]
}

=== cpp-love/The-Hidden-Route/assets/json/level1.json
{
    "$schema": "../../schema/level-v0.1.0-4.schema.json",
    "level_script": "level1.lua",
    "segments": [
        {
            "start_center": {
                "x": 200,
                "y": 200
            },
            "length": 300,
            "dir": "right",
            "next": 1
        },
        {
            "start_center": {
                "x": 500,
                "y": 200
            },
            "length": 100,
            "dir": "down",
            "prev": 0,
            "next": 2
        },
        {
            "start_center": {
                "x": 500,
                "y": 300
            },
            "length": 250,
            "dir": "left",
            "prev": 1,
            "next": 3
        },
        {
            "start_center": {
                "x": 250,
                "y": 300
            },
            "length": 80,
            "dir": "up",
            "prev": 2,
            "tags": [
                0
            ]
        },
        {
            "start_center": {
                "x": 250,
                "y": 180
            },
            "length": 130,
            "dir": "up",
            "next": 5
        },
        {
            "start_center": {
                "x": 250,
                "y": 50
            },
            "length": 250,
            "dir": "right",
            "prev": 4,
            "next": 6
        },
        {
            "start_center": {
                "x": 500,
                "y": 50
            },
            "length": 100,
            "dir": "down",
            "prev": 5,
            "next": 7
        },
        {
            "start_center": {
                "x": 500,
                "y": 150
            },
            "length": 150,
            "dir": "left",
            "prev": 6,
            "next": 8
        },
        {
            "start_center": {
                "x": 350,
                "y": 150
            },
            "length": 80,
            "dir": "up",
            "prev": 7,
            "tags": [
                1
            ]
        },
        {
            "start_center": {
                "x": 520,
                "y": 50
            },
            "length": 80,
            "dir": "right"
        }
    ],
    "line_strips": {
        "vertexs": [
            [
                {
                    "x": 260,
                    "y": 210
                },
                {
                    "x": 260,
                    "y": 290
                },
                {
                    "x": 490,
                    "y": 290
                },
                {
                    "x": 490,
                    "y": 210
                },
                {
                    "x": 190,
                    "y": 210
                },
                {
                    "x": 190,
                    "y": 190
                },
                {
                    "x": 510,
                    "y": 190
                },
                {
                    "x": 510,
                    "y": 310
                },
                {
                    "x": 240,
                    "y": 310
                },
                {
                    "x": 240,
                    "y": 210
                }
            ],
            [
                {
                    "x": 240,
                    "y": 190
                },
                {
                    "x": 240,
                    "y": 40
                },
                {
                    "x": 510,
                    "y": 40
                },
                {
                    "x": 510,
                    "y": 160
                },
                {
                    "x": 340,
                    "y": 160
                },
                {
                    "x": 340,
                    "y": 60
                }
            ],
            [
                {
                    "x": 260,
                    "y": 190
                },
                {
                    "x": 260,
                    "y": 60
                },
                {
                    "x": 490,
                    "y": 60
                },
                {
                    "x": 490,
                    "y": 140
                },
                {
                    "x": 360,
                    "y": 140
                },
                {
                    "x": 360,
                    "y": 60
                }
            ],
            [
                {
                    "x": 510,
                    "y": 40
                },
                {
                    "x": 610,
                    "y": 40
                },
                {
                    "x": 610,
                    "y": 60
                },
                {
                    "x": 510,
                    "y": 60
                }
            ]
        ],
        "width": 5
    },
    "level_info": {
        "start_segment_entity": 0,
        "end_segment_entity": 9
    }
}
